description: |
  This API supports Pass Through Authentication.
type: Pass Through
describedBy:
  headers:
    Api-Key:
      type: string
      description: A value to authenticate API request.
      example: bDVKRW1jUjJ2oNWdGFfMTY1MjIwNTEzOA==
  responses:
    401:
