headers:
  Accept:
    type: string
    description: A value to declare the expected data type from the API response.
    example: application/json
  Client:
    type: string
    description: A value to declare the domain name of client submitting the API request.
    example: zerotwomanagement.com
  Content-Type:
    type: string
    description: A value to declare the data type sent with the API request.
    example: application/json
  Sandbox:
    type: boolean
    description: A value to test the API request in sandbox mode.
    example: false
